### ISSUE TITLE
AttributeError: module 'scipy.stats' has no attribute 'median_absolute_deviation'

### ISSUE THREAD

**Issue by MislavSag** [fraunhoferportugal/tsfel#123]
Hi,

I have installed tsfel in an empty virtual environment inside Dockerfile:
```
# install python and packages
RUN apt-get -y install python3 python3-venv python3-pip
RUN python3 -m venv /home/rstudio/venv
RUN /home/rstudio/venv/bin/pip3 install --upgrade pip setuptools wheel
RUN /home/rstudio/venv/bin/pip3 install tsfel
```

When I want to extract all features, I get an error:
```
! AttributeError: module 'scipy.stats' has no attribute 'median_absolute_deviation'
```

**Comment by MislavSag** [comment]
On this site: https://github.com/scipy/scipy/releases/tag/v1.9.0

it says 

Removed stats.median_absolute_deviation

Maybe the package doesn't work with scipy 1.9.0 and above ?

**Comment by dmfolgado** [comment]
Hi! Correct, the latest scipy stable released has changed the name to [`scipy.stats.median_abs_deviation`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.median_abs_deviation.html). We'll look onto this. For now I recommend that you downgrade the scipy release (e.g. pip install scipy==1.8.1).

**Comment by ErikHodges** [comment]
> Hi! Correct, the latest scipy stable released has changed the name to [`scipy.stats.median_abs_deviation`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.median_abs_deviation.html). We'll look onto this. For now I recommend that you downgrade the scipy release (e.g. `pip install scipy==1.8.1`).

To fix this, I changed line 661 of the '\tsfel\feature_extraction\features.py' script from:

return scipy.stats.median_**absolute**_deviation(signal, scale=1)
--to--
return scipy.stats.median_**abs**_deviation(signal, scale=1)

Hope this helps!

**Comment by sp435** [comment]
> Restarted the system after making the change. Thank you!

**Comment by mluacnunes** [comment]
Updated on new release v0.1.5
